wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1630204198
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.8.5
      5: 0.12.1
      8:
      - 5
batch_size:
  desc: null
  value: 64
criterion:
  desc: null
  value: cross_entropy
data_dir:
  desc: null
  value: /opt/ml/input/data/train/images
dataset:
  desc: null
  value: MaskBaseDataset
epochs:
  desc: null
  value: 5
log_interval:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001
lr_decay_step:
  desc: null
  value: 20
model:
  desc: null
  value: BaseModel
model_dir:
  desc: null
  value: ./model
name:
  desc: null
  value: exp
optimizer:
  desc: null
  value: Adam
resize:
  desc: null
  value:
  - 128
  - 96
seed:
  desc: null
  value: 42
transform:
  desc: null
  value: BaseTransform
val_batch_size:
  desc: null
  value: 1000
val_ratio:
  desc: null
  value: 0.2
